### ISSUE TITLE
Woonsituatie moet opnieuw gemodelleerd worden 

### ISSUE THREAD

**Issue by ogieling** [Nictiz/Nictiz-CDA-BgZ2020#1]
De Zib nl.zorg.Woonsituatie uit 2017 bevat als data "WoningType" en "toelichting". In de bijbehorende CDA template is dit gemodelleerd als gelijk waardig (woonsituatie = woningtype).

De Zib nl.zorg.Woonsituatie uit 2020 heeft als aanvulling bij data "WoningAanpassing" en "WoonOmstandigheid" gelijkwaardig met "WoningType" moet komen. 

Deze aanpassing vereist een besluit over de een nieuw model.
Gaan we dit toevoegen door alle 3 de onderdeler toe te voegen als een Oberservation. Maken we gebruik van een Organizer?

[https://zibs.nl/wiki/Woonsituatie-v3.3(2020NL)](url)
[http://decor.nictiz.nl/pub/bgz2017/bgz2017-html-20180509T190557/ds-2.16.840.1.113883.2.4.3.11.60.40.3.7.8-2017-09-04T000000.html](url)

**Comment by mgraauw** [comment]
Ik heb deze al toegevoegd, als entries bij de Observation:
https://decor.nictiz.nl/art-decor/decor-templates--zib2020bbr-?section=templates&id=2.16.840.1.113883.2.4.3.11.60.121.10.8&effectiveDate=2021-06-08T11:13:16&language=nl-NL
